import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { ReactNode } from 'react';
import { routing } from '@/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
import { ThemeProvider } from "@/providers/theme-providers";
import Navbar from "@/components/Navbar";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={` antialiased`}>
        <ThemeProvider>
          <NextIntlClientProvider >
            <header className="p-4 border-b border-gray-300 dark:border-gray-700">
              <Navbar />
            </header>
            <main className="p-6">
              {children}
            </main>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
